default: &default
  adapter: postgresql
  encoding: unicode
  host: db_match_app
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: myapp_development


test:
  <<: *default
  database: myapp_test

production:
   adapter: mysql2
   encoding: utf8
   reconnect: false
   database: mysql
   pool: 5     